CREATE TABLE IF NOT EXISTS green_taxi (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    VendorID VARCHAR(256),
    lpep_pickup_datetime VARCHAR(256),
    lpep_dropoff_datetime VARCHAR(256),
    passenger_count VARCHAR(256),
    trip_distance VARCHAR(256),
    RatecodeID VARCHAR(256),
    store_and_fwd_flag VARCHAR(256),
    PULocationID VARCHAR(256),
    DOLocationID VARCHAR(256),
    payment_type VARCHAR(256),
    fare_amount VARCHAR(256),
    extra VARCHAR(256),
    mta_tax VARCHAR(256),
    tip_amount VARCHAR(256),
    tolls_amount VARCHAR(256),
    improvement_surcharge VARCHAR(256),
    total_amount VARCHAR(256),
    ehail_fee VARCHAR(256),
    trip_type VARCHAR(256),
    congestion_surcharge VARCHAR(256),
    cbd_congestion_fee VARCHAR(256)
);