CREATE TABLE IF NOT EXISTS green_taxi (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    VendorID INT,
    lpep_pickup_datetime VARCHAR(30),
    lpep_dropoff_datetime VARCHAR(30),
    passenger_count INT,
    trip_distance FLOAT,
    RatecodeID INT,
    store_and_fwd_flag VARCHAR(1),
    PULocationID INT,
    DOLocationID INT,
    payment_type INT,
    fare_amount FLOAT,
    extra FLOAT,
    mta_tax FLOAT,
    tip_amount FLOAT,
    tolls_amount FLOAT,
    improvement_surcharge FLOAT,
    total_amount FLOAT,
    ehail_fee FLOAT,
    trip_type FLOAT,
    congestion_surcharge FLOAT,
    cbd_congestion_fee FLOAT
);